version: "3.9"
services:
    redis:
        image: redis:7-alpine
        restart: always
        container_name: redis
        ports: ["6379:6379"]
        volumes:
            - ./private/redis:/data
    db:
        image: postgres:14-alpine
        restart: always
        container_name: postgres
        env_file: ".env"
        ports: ["5432:5432"]
        volumes:
            - ./private/pgdata:/var/lib/postgresql/data
