version: "3.9"
services:
    redis:
        image: redis:7-alpine
        restart: always
        container_name: redis
        ports: ["6379:6379"]
    db:
        image: postgres:14-alpine
        restart: always
        container_name: postgres
        ports: ["5432:5432"]
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=movies
