version: "3.9"
services:
    db:
        image: postgres:14-alpine
        restart: always
        container_name: postgres
        env_file: ".env"
        ports: ["5432:5432"]
        volumes:
            - ./pgdata:/var/lib/postgresql/data
