version: "3.9"
services:
    db:
        image: postgres:14-alpine
        restart: always
        container_name: postgres-testing
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
            POSTGRES_DB: "movies"
        ports: ["5432:5432"]
